<a href="https://colab.research.google.com/github/dudns1234/Data_Analysis/blob/master/02_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(items)

labels = encoder.transform(items)

# Estimator : 추정(예측)
# Transformer : 변환


In [ ]:
# 변환 결과 확인
print("인코딩 변환 값 : {}".format(labels))
print("인코딩 변환 값 : {}".format(encoder.classes_))
print("인코딩 변환 값 : {}".format(encoder.inverse_transform([1,5,2,3,1,0,1,3,5,4,1,2,0])))

인코딩 변환 값 : [0 1 4 5 3 3 2 2]
인코딩 변환 값 : ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']
인코딩 변환 값 : ['냉장고' '컴퓨터' '믹서' '선풍기' '냉장고' 'TV' '냉장고' '선풍기' '컴퓨터' '전자렌지' '냉장고' '믹서'
 'TV']


## 원-핫 인코딩(One-Hot Encoding)
- 2차원 배열 사용
- 원-핫 인코딩은 보통 Feature에 활용되기 때문

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# 2차원 ndarray로 변환
items_arr = np.array(items).reshape(-1,1) # (N,1)로 변환 => 행이 N개, 열이 1개
items_arr

array([['TV'],
       ['냉장고'],
       ['전자렌지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U4')

In [ ]:
encoder = OneHotEncoder()

ohe_labels = encoder.fit_transform(items_arr)
ohe_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [ ]:
# 1의 위치를 압축된 표현으로 보기
print(ohe_labels)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0


In [ ]:
# 압축된 형식을 풀어서 표현하기
print(ohe_labels.toarray())

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


#### Min-Max Scaling(정규화)
column 간에 다른 **min, max**값을 가지는 경우, **정규화**를 통해서 최대 / 최소의 척도를 하나로 맞춰 주는 작업
* 최소를 0으로, 최대를 1로 설정
------
* 네이버 영화 평점 ( 0 ~ 10 ) : [2, 4, 6, 8, 10]
* 넷플릭스 영화 평점 ( 0 ~ 5 ) : [1, 2, 3, 4, 5]


In [ ]:
import pandas as pd
movie_score = pd.DataFrame({
    "naver":[0, 2, 4, 6, 8],
    "netflix":[1, 2, 3, 4, 5]
})

movie_score

naver  netflix
0      0        1
1      2        2
2      4        3
3      6        4
4      8        5

## StandardScaling(표준화)
- 평균이 0, 표준편차가 1이 되도록 변환

In [ ]:
data1 = np.array([100, 110, 120, 130, 140])
data2 = np.array([0, 1, 2, 3, 4])

In [ ]:
data1.mean(), data1.std(), data1.var()

(120.0, 14.142135623730951, 200.0)

In [ ]:
data2.mean(), data2.std(), data2.var()

(2.0, 1.4142135623730951, 2.0)

In [ ]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

In [ ]:
data1_scaled = std_scaler.fit_transform(data1.reshape(-1,1))
data2_scaled = std_scaler.fit_transform(data2.reshape(-1,1))

In [ ]:
print(data1_scaled)
print('----------------')
print(data2_scaled)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
----------------
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
